### ISSUE TITLE
remove travis integration

### ISSUE THREAD

**Issue by goern** [thoth-station/result-api#15]
We dont need it here, dont we?!

**Comment by fridex** [comment]
It was [removed](https://github.com/thoth-station/result-api/commit/ad0fb3682376d91f85fe136c9f73fd276a2e8dce), no? I cannot see it in the code tree.

**Comment by goern** [comment]
oh, you are right, nevertheless travis build PR #14 

https://travis-ci.org/thoth-station/result-api/builds/370736670?utm_source=github_status&utm_medium=notification

**Comment by fridex** [comment]
Agh, right. I've just removed it form [monitored repos](https://travis-ci.org/profile/thoth-station) by travis ci. You should have admin rights as well if you sign with github.

I think there will be other leftovers thought.

**Comment by goern** [comment]
right, lets remove them as they pop up
